import math

# Those below are game settings.
RES = WIDTH, HEIGHT = 1600, 900
HALF_WIDTH = WIDTH // 2
HALF_HEIGHT = HEIGHT // 2
FPS = 60

PLAYER_POS = 5.6, 5.6     # mini_map
PLAYER_ANGLE = 0
PLAYER_SPEED = 0.003
PLAYER_ROT_SPEED = 0.0004
PLAYER_SIZE_SCALE = 160
PLAYER_MAX_HEALTH = 100
PLAYER_MAX_HUNGER = 100

MOUSE_SENSITIVITY = 0.00015
MOUSE_MAX_REL = 25
MOUSE_BORDER_LEFT = 100
MOUSE_BORDER_RIGHT = WIDTH - MOUSE_BORDER_LEFT

FLOOR_COLOR = (30, 30, 30)

FOV = math.pi / 3
HALF_FOV = FOV / 2
NUM_RAYS = WIDTH // 2
HALF_NUM_RAYS = NUM_RAYS // 2
DELTA_ANGLE = FOV / NUM_RAYS
MAX_DEPTH = 20

SCREEN_DIST = HALF_WIDTH / math.tan(HALF_FOV)
SCALE = WIDTH // NUM_RAYS

TEXTURE_SIZE = 256
HALF_TEXTURE_SIZE = TEXTURE_SIZE // 2
